/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trivia.game.pkgfinal.project;

import java.util.HashSet;

/**
 *
 * @author nigol
 */
public class Start extends javax.swing.JFrame {

    /**
     * Creates new form Results
     */
    public Start() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(51, 153, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome To World Trivia!");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Start Game");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 3, true));

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnStart)
                        .addGap(306, 306, 306))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnStart)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        setVisible(false);
        
        HashSet<Integer> done = new HashSet<>(); // answers done
        while (done.size() < 10){
            int q = (int) (Math.random() * 10) + 1;
            if (!done.contains(q)){
                doQuestion(q, done.size() + 1);
                done.add(q);
                if (Question.quit)break;
            }
        }
        
        Results res = new Results(Question.trivanswered, Question.marks);
        res.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_btnStartActionPerformed

    
    private void doQuestion(int q, int num) {
        switch (q) {
            case 1 -> {
                String[] choices1 = {"2005","2006","2007","2008"};
                Question q1 = new Question(num, "What year was the very first model of the iPhone released?", choices1, 2);
                q1.setVisible(true);
            }
            case 2 -> {
                String[] choices2 = {"Right-click and select \"Copy\"","Atl + Enter","Ctrl + V","Ctrl + C"};
                Question q2 = new Question(num, "What’s the shortcut for the “copy” function on most computers?", choices2, 3);
                q2.setVisible(true);
            }
            case 3 -> {
                String[] choices3 = {"100","108","52","74"};
                Question q3 = new Question(num, "How many cards are there in a deck of UNO?", choices3, 1);
                q3.setVisible(true);
            }
            case 4 -> {
                String[] choices4 = {"Monopoly","Life","Risk","Guess Who?"};
                Question q4 = new Question(num, "Which game includes the phrase \"Do not pass go, do not collect $200\"?", choices4, 0);
                q4.setVisible(true);
            }
            case 5 -> {
                String[] choices5 = {"Clark","Kal-El","Krypton","Bruce"};
                Question q5 = new Question(num, "What was Superman's birth name?", choices5, 1);
                q5.setVisible(true);
            }
            case 6 -> {
                String[] choices6 = {"Earth","Mars","Saturn","Jupiter"};
                Question q6 = new Question(num, "Which planet has the most gravity?", choices6, 3);
                q6.setVisible(true);
            }
            case 7 -> {
                String[] choices7 = {"One","Two","Three","Four"};
                Question q7 = new Question(num, "How many molecules of oxygen does Ozone have?", choices7, 2);
                q7.setVisible(true);
            }
            case 8 -> {
                String[] choices8 = {"District of Columbia","Detective Comics","Dance Challenge","Direct Current"};
                Question q8 = new Question(num, "What does the 'DC' in DC Comics stand for?", choices8, 1);
                q8.setVisible(true);
            }
            case 9 -> {
                String[] choices9 = {"The Lion King","The Phantom of the Opera","Wicked","Hamilton"};
                Question q9 = new Question(num, "Which show is the highest-grossing production on Broadway ever?", choices9, 0);
                q9.setVisible(true);
            }
            case 10 -> {
                String[] choices10 = {"About 100 years","About 500 years","About 1000 years","About 2000 years"};
                Question q10 = new Question(num, "How long did the Middle Ages last?", choices10, 2);
                q10.setVisible(true);
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
